services:
  notes_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: notes_server
    networks:
      - notes-network
    ports:
      - "4000:4000"  # Add this line testerror
    expose:
      - 4000
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SECRET=wachter18
      - MONGODB_URI=mongodb+srv://nwachter:wachter18@clusterprojects.oeemd.mongodb.net/ProjetNotes?retryWrites=true&w=majority&appName=ClusterProjects
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  notes_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: notes_client
    networks:
      - notes-network
    ports:
      - "3001:3001"  # Also expose client port testerror
    expose:
      - 3001
    environment:
      - REACT_APP_API_URL=https://glass-notes.nwproject.fr
      #- REACT_APP_API_URL=http://localhost:4000
      - NODE_ENV=production
    depends_on:
      - notes_server
    restart: unless-stopped

networks:
  notes-network:
    name: notes-network
    external: true